BonoboBundle\Entity\BonoboFriends:
    type: entity
    table: bonobo_friends
    indexes:
        user-fk:
            columns:
                - user-fk
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        age:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        famille:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        race:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        nourriture:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    manyToOne:
        userFk:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user-fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
