<?php

namespace BonoboBundle\Repository;

/**
 * BonoboFriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonoboFriendsRepository extends \Doctrine\ORM\EntityRepository
{
}
